---
"num_cpcs": 3
"data_dir": 'C:\Users\user\Box\Jen Lab Data Archive\SADR_2'
cpc1:
  "cpc_name": "SADDEST"
  "serial_port": "COM3"
  "serial_baud": 115200
  "serial_bytesize": 8
  "serial_parity": "N"
  "serial_timeout": 0.5
  "start_commands" : ['psld,12', 'log,1']
  "default_flow" : True
  "cpc_flowrate" : 0 
  "serial_commands": []
  "cpc_header" : [cpc name,datetime,instrument_datetime,concentration,condenser_temperature,initiator_temperature,moderator_temperature,optics_temperature,moderator_heatsink_temperature,board_temperature,condenser_heatsink_temperature,differential_pressure,absolute_pressure,flow_rate,interval_time,corrected_live_time,measured_dead_time,xx,xxx,flags,flags_character,serial_number]
cpc2:
  "cpc_name": "BLANKEST"
  "serial_port": "COM6"
  "serial_baud": 115200
  "serial_bytesize": 8
  "serial_parity": "N"
  "serial_timeout": 0.5
  "start_commands" : ['psld,12', 'log,1']
  "default_flow" : True
  "cpc_flowrate" : 0 
  "serial_commands": []
  "cpc_header" : [cpc name,datetime,instrument_datetime,concentration,condenser_temperature,initiator_temperature,moderator_temperature,optics_temperature,moderator_heatsink_temperature,board_temperature,condenser_heatsink_temperature,differential_pressure,absolute_pressure,flow_rate,interval_time,corrected_live_time,measured_dead_time,xx,xxx,flags,flags_character,serial_number]
cpc3:
  "cpc_name": "Outdoor"
  "serial_port": "COM4"
  "serial_baud": 115200
  "serial_bytesize": 8
  "serial_parity": "N"
  "serial_timeout": 0.5
  "start_commands" : ['psld,12', 'log,1']
  "default_flow" : True
  "cpc_flowrate" : 0 
  "serial_commands": []
  "cpc_header" : [cpc name,datetime,instrument_datetime,concentration,condenser_temperature,initiator_temperature,moderator_temperature,optics_temperature,moderator_heatsink_temperature,board_temperature,condenser_heatsink_temperature,differential_pressure,absolute_pressure,flow_rate,interval_time,corrected_live_time,measured_dead_time,xx,xxx,flags,flags_character,serial_number]
# cpc0:
#   "cpc_name": "ADI CPC"
#   "serial_port": "COM4"
#   "serial_baud": 115200
#   "serial_bytesize": 8
#   "serial_parity": "N"
#   "serial_timeout": 0.5
#   "start_commands" : ['psld,12', 'log,1']
#   "default_flow" : True
#   "cpc_flowrate" : 0 
#   "serial_commands": []
#   "cpc_header" : [cpc name,datetime,instrument_datetime,concentration,condenser_temperature,initiator_temperature,moderator_temperature,optics_temperature,moderator_heatsink_temperature,board_temperature,condenser_heatsink_temperature,differential_pressure,absolute_pressure,flow_rate,interval_time,corrected_live_time,measured_dead_time,xx,xxx,flags,flags_character,serial_number]
# cpc0:
#   "cpc_name": "3025"
#   "serial_port": "COM7"
#   "serial_baud": 9600
#   "serial_bytesize": 7
#   "serial_parity": "E"
#   "serial_timeout": 0.05
#   "start_commands" : ['TS350','TO370']
#   "default_flow" : True
#   "cpc_flowrate" : 0.7833 # 300/60 cubic centimeters per second
#   "serial_commands": ['RD','R1','R2','R3','R4','R5','R6','R7','RE','RB','R0']
#   "cpc_header" : ["cpc name","datetime","concentration","condensor temp","saturator temp","optics temp","flow","ready environment","reference detector voltage","detector voltage","pump control value","1 second counts","liquid level"]
