---
pulse_count : True
cpc : "3025"
labjack : "ANY"
labjack_io :
  "flow_read_input": "AIN0"
  "voltage_monitor_input": "AIN1"
  "press_input": "AIN2"
  "temp_input": "AIN3"
  "rh_input": "AIN4"
  "voltage_set_pos": "TDAC2"
  "voltage_set_neg": "TDAC3"
  "flow_set_output": "DAC1"
  "counter": "DIO18"
  "width": "DIO0"
  "fill_valve" : "DIO3"
# cpc_config:
#   "cpc_flowrate" : 0.7833 # 300/60 cubic centimeters per second
data_config:
  "header": ["Count","Timer","Elapsed Time","Set Diameter [nm]","Calculated Diameter [nm]","Set Voltage [V]","Actual Voltage [V]","Flow Rate [LPM]","Temperature [C]","RH [%]","Pressure [kPa]","Concentration [#/cc]","Concentration No Deadtime[#/cc]","Counts [#]","Pulse Width [s]","Pulse Width Error [%]","Blower Control Runtime [s]","Voltage Update Runtime [s]","Voltage Monitor Runtime [s]","CPC Counting Runtime [s]","Datalogging Runtime[s]"]
  "serial_commands": ['RD','R1','R2','R3','R4','R5','R6','R7','RE','RB','R0']
  "cpc_header" :  ['time','concentration','condensor temp','saturator temp','optics temp','flow','ready environment','reference detector voltage','detector voltage','pump control value','1 second counts','liquid level']
  "serial_port": "COM6"
  "serial_baud": 9600
  "serial_bytesize": 7
  "serial_parity": "E"
  "serial_timeout": 0.05
  "start_commands" : ['TS440','TO460']
  "default_flow" : False
  "cpc_flowrate" : 0.7833 # 300/60 cubic centimeters per second
ion_config:
  "toggle_seconds" : 60
  "precip_volt" : 600
  "supply_scaling" : 200